image: relearn-ci

build:
  stage: build
  # instead of calling g++ directly you can also use some build toolkit like make
  # install the necessary build tools when needed
  # before_script:
  #   - apt update && apt -y install make autoconf
  before_script:
    - cd relearn && mkdir build-docker && cd build-docker  
  script:
    - cmake -Dnoclangtidy=1 .. && make -j 16
  artifacts:
    paths:
      - relearn/build-docker
      #- mybinary
      # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
      # cache:
      #   paths:
      #     - "*.o"

# run tests using the binary built before
test:
  stage: test
  script:
    - relearn/build-docker/runTests
  dependencies: 
    - build
  artifacts:
    paths:
      - relearn/build-docker
