build-mpi:
  image: relearn-ci
  stage: build
  before_script:
    - cd relearn && mkdir build-docker && cd build-docker  
  script:
    - cmake -Dnoclangtidy=1 .. && make -j 16
  artifacts:
    paths:
      - relearn/build-docker

# run tests using the binary built before
test-mpi:
  image: relearn-ci
  stage: test
  script:
    - relearn/build-docker/runTests
  dependencies: 
    - build-mpi
  artifacts:
    paths:
      - relearn/build-docker

build-nompi:
  image: relearn-ci-nompi
  stage: build
  before_script:
    - cd relearn && mkdir build-docker-nompi && cd build-docker-nompi  
  script:
    - cmake -Dnoclangtidy=1 .. && make -j 16
  artifacts:
    paths:
      - relearn/build-docker-nompi

# run tests using the binary built before
test-nompi:
  image: relearn-ci-nompi
  stage: test
  script:
    - relearn/build-docker-nompi/runTests
  dependencies: 
    - build-nompi
  artifacts:
    paths:
      - relearn/build-docker-nompi

build-graph:
  image: relearn-ci
  stage: build
  before_script:
    - cd graph && mkdir build-docker && cd build-docker  
  script:
    - cmake -Dnoclangtidy=1 .. && make -j 16
  artifacts:
    paths:
      - graph/build-docker
      
# run tests using the binary built before
test-graph:
  image: relearn-ci
  stage: test
  script:
    - graph/build-docker/test/runTests
  dependencies: 
    - build-graph
  artifacts:
    paths:
      - graph/build-docker
      
   
deploy-single:
  image: relearn-ci
  stage: deploy
  script:
    - relearn/build-docker/relearn --steps 2000 --file relearn/input/positions.txt --graph relearn/input/network.txt --synaptic-elements-lower-bound 1.3 --synaptic-elements-upper-bound 1.7 --openmp 12
  dependencies:
    - test-mpi
  artifacts:
    paths:
      - relearn/build-docker  

deploy-create:
  image: relearn-ci
  stage: deploy
  script:
    - relearn/build-docker/relearn --steps 2000 --file relearn/input/positions.txt --graph relearn/input/network.txt --synaptic-elements-lower-bound 1.3 --synaptic-elements-upper-bound 1.7 --openmp 12 --creation-interrupts relearn/input/tests/create-100-interrupt.txt
  dependencies:
    - test-mpi
  artifacts:
    paths:
      - relearn/build-docker     

deploy-disable:
  image: relearn-ci
  stage: deploy
  script:
    - relearn/build-docker/relearn --steps 2000 --file relearn/input/positions.txt --graph relearn/input/network.txt --synaptic-elements-lower-bound 1.3 --synaptic-elements-upper-bound 1.7 --openmp 12 --disable-interrupts relearn/input/tests/disable-100-interrupt.txt
  dependencies:
    - test-mpi
  artifacts:
    paths:
      - relearn/build-docker    

deploy-enable:
  image: relearn-ci
  stage: deploy
  script:
    - relearn/build-docker/relearn --steps 2000 --file relearn/input/positions.txt --graph relearn/input/network.txt --synaptic-elements-lower-bound 1.3 --synaptic-elements-upper-bound 1.7 --openmp 12 --enable-interrupts relearn/input/tests/enable-100-interrupt.txt
  dependencies:
    - test-mpi
  artifacts:
    paths:
      - relearn/build-docker     
  
deploy-single-nompi:
  image: relearn-ci-nompi
  stage: deploy
  script:
    - relearn/build-docker-nompi/relearn --steps 2000 --file relearn/input/positions.txt --graph relearn/input/network.txt --synaptic-elements-lower-bound 1.3 --synaptic-elements-upper-bound 1.7 --openmp 12
  dependencies:
    - test-nompi
  artifacts:
    paths:
      - relearn/build-docker-nompi 
      
deploy-create-nompi:
  image: relearn-ci-nompi
  stage: deploy
  script:
    - relearn/build-docker-nompi/relearn --steps 2000 --file relearn/input/positions.txt --graph relearn/input/network.txt --synaptic-elements-lower-bound 1.3 --synaptic-elements-upper-bound 1.7 --openmp 12 --creation-interrupts relearn/input/tests/create-100-interrupt.txt
  dependencies:
    - test-nompi
  artifacts:
    paths:
      - relearn/build-docker-nompi     

deploy-disable-nompi:
  image: relearn-ci-nompi
  stage: deploy
  script:
    - relearn/build-docker-nompi/relearn --steps 2000 --file relearn/input/positions.txt --graph relearn/input/network.txt --synaptic-elements-lower-bound 1.3 --synaptic-elements-upper-bound 1.7 --openmp 12 --disable-interrupts relearn/input/tests/disable-100-interrupt.txt
  dependencies:
    - test-nompi
  artifacts:
    paths:
      - relearn/build-docker-nompi    

deploy-enable-nompi:
  image: relearn-ci-nompi
  stage: deploy
  script:
    - relearn/build-docker-nompi/relearn --steps 2000 --file relearn/input/positions.txt --graph relearn/input/network.txt --synaptic-elements-lower-bound 1.3 --synaptic-elements-upper-bound 1.7 --openmp 12 --enable-interrupts relearn/input/tests/enable-100-interrupt.txt
  dependencies:
    - test-nompi
  artifacts:
    paths:
      - relearn/build-docker-nompi    
      
   
deploy-mpi-1:
  image: relearn-ci
  stage: deploy
  script:
    - mpiexec -n 1 relearn/build-docker/relearn --steps 2000 --file relearn/input/positions.txt --graph relearn/input/network.txt --synaptic-elements-lower-bound 1.3 --synaptic-elements-upper-bound 1.7 --openmp 12
  dependencies:
    - test-mpi
  artifacts:
    paths:
      - relearn/build-docker 
      
   
deploy-mpi-2:
  image: relearn-ci
  stage: deploy
  script:
    - mpiexec -n 2 relearn/build-docker/relearn --steps 2000 --file relearn/input/positions.txt --graph relearn/input/network.txt --synaptic-elements-lower-bound 1.3 --synaptic-elements-upper-bound 1.7 --openmp 12
  dependencies:
    - test-mpi
  artifacts:
    paths:
      - relearn/build-docker 
      
   
deploy-mpi-4:
  image: relearn-ci
  stage: deploy
  script:
    - mpiexec -n 4 relearn/build-docker/relearn --steps 2000 --file relearn/input/positions.txt --graph relearn/input/network.txt --synaptic-elements-lower-bound 1.3 --synaptic-elements-upper-bound 1.7 --openmp 12
  dependencies:
    - test-mpi
  artifacts:
    paths:
      - relearn/build-docker 
      
   
deploy-mpi-8:
  image: relearn-ci
  stage: deploy
  script:
    - mpiexec -n 8 relearn/build-docker/relearn --steps 2000 --file relearn/input/positions.txt --graph relearn/input/network.txt --synaptic-elements-lower-bound 1.3 --synaptic-elements-upper-bound 1.7 --openmp 12
  dependencies:
    - test-mpi
  artifacts:
    paths:
      - relearn/build-docker 
