build-mpi:
  image: relearn-ci
  stage: build
  before_script:
    - cd relearn && mkdir build-docker && cd build-docker  
  script:
    - cmake -Dnoclangtidy=1 .. && make -j 16
  artifacts:
    paths:
      - relearn/build-docker

# run tests using the binary built before
test-mpi:
  image: relearn-ci
  stage: test
  script:
    - relearn/build-docker/runTests
  dependencies: 
    - build-mpi
  artifacts:
    paths:
      - relearn/build-docker

build-nompi:
  image: relearn-ci-nompi
  stage: build
  before_script:
    - cd relearn && mkdir build-docker-nompi && cd build-docker-nompi  
  script:
    - cmake -Dnoclangtidy=1 .. && make -j 16
  artifacts:
    paths:
      - relearn/build-docker-nompi

# run tests using the binary built before
test-nompi:
  image: relearn-ci-nompi
  stage: test
  script:
    - relearn/build-docker-nompi/runTests
  dependencies: 
    - build-nompi
  artifacts:
    paths:
      - relearn/build-docker-nompi

build-graph:
  image: relearn-ci
  stage: build
  before_script:
    - cd graph && mkdir build-docker && cd build-docker  
  script:
    - cmake -Dnoclangtidy=1 .. && make -j 16
  artifacts:
    paths:
      - graph/build-docker
      
test-graph:
  image: relearn-ci
  stage: test
  script:
    - graph/build-docker/test/runTests
  dependencies: 
    - build-graph
  artifacts:
    paths:
      - graph/build-docker
