option(ENABLE_CUDA "Enable cuda" ON)
set(CUDA_FOUND OFF)
if(ENABLE_CUDA)
  check_language(CUDA)
  if(CMAKE_CUDA_COMPILER)
    set(CUDA_SEPARABLE_COMPILATION ON)
    enable_language(CUDA)
    set(CUDA_FOUND ON)
    set(POSITION_INDEPENDENT_CODE ON)
    add_compile_definitions(CUDA_FOUND=true)
    set_property(GLOBAL PROPERTY CUDA_ARCHITECTURES 61)
    
  else()
    message("CUDA was enabled but not found. Disabling it.")
    add_compile_definitions(CUDA_FOUND=false)
  endif()
  else()
  add_compile_definitions(CUDA_FOUND=false)
endif()