FROM nvidia/cuda:11.8.0-devel-ubuntu22.04


RUN apt-get update

RUN DEBIAN_FRONTEND=noninteractive apt-get install -qq -y build-essential wget m4 flex bison cmake git software-properties-common
RUN add-apt-repository -y ppa:ubuntu-toolchain-r/test
RUN apt-get update
RUN apt-get install -y gcc-11
#RUN wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-ubuntu2004.pin
#RUN mv cuda-ubuntu2004.pin /etc/apt/preferences.d/cuda-repository-pin-600
#RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/7fa2af80.pub
#RUN add-apt-repository "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/ /"
#RUN apt-get update 
#RUN apt-get -y install cuda
#RUN wget https://developer.download.nvidia.com/compute/cuda/11.4.4/local_installers/cuda_11.4.4_470.82.01_linux.run
#RUN sh cuda_11.4.4_470.82.01_linux.run --help
#RUN sh cuda_11.4.4_470.82.01_linux.run --silent --toolkit --no-opengl-libs
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y clang-tidy
RUN apt-get install -y libboost-all-dev
RUN apt-get install -y libglu1-mesa-dev
RUN apt-get install -y freeglut3-dev
RUN apt-get install -y mesa-common-dev
RUN apt-get install -y mpich libmpich-dev

RUN ln -nsf /usr/bin/mpicxx.mpich /etc/alternatives/mpicc
RUN ln -nsf /usr/bin/mpicxx.mpich /etc/alternatives/mpiCC
RUN ln -nsf /usr/bin/mpicxx.mpich /etc/alternatives/mpic++
RUN ln -nsf /usr/bin/mpicxx.mpich /etc/alternatives/mpicxx
RUN ln -nsf /usr/bin/mpiexec.mpich /etc/alternatives/mpiexec
RUN ln -nsf /usr/bin/mpif77.mpich /etc/alternatives/mpif77
RUN ln -nsf /usr/bin/mpif90.mpich /etc/alternatives/mpif90
RUN ln -nsf /usr/bin/mpifort.mpich /etc/alternatives/mpifort
RUN ln -nsf /usr/bin/mpirun.mpich /etc/alternatives/mpirun

CMD [ "/bin/bash" ]
